Example
vaad23/IJuniorBasicLevelTask5 pull request #1
Opened 2020-06-04 12:36 UTC by vaad23

Решение домашнего задания в отдельной ветке и добавление его в основную.

2020-06-08 06:59 UTC, HolyMonkey requested changes

2020-06-08 06:59 UTC, HolyMonkey commented on Assets/Scripts/Ground.cs
> +public class Ground : MonoBehaviour
Слабо написано, у тебя на каждый объект создаётся кучка кода. Представь что нам бы хотелось в будущем добавлять допустим пики (которые замедляют) и что-нибудь ещё.

2020-06-08 06:59 UTC, HolyMonkey commented on Assets/Scripts/GroundTracking.cs
> +        private set
Слишком сложная логика в сеттере

2020-06-08 06:59 UTC, HolyMonkey commented on Assets/Scripts/GroundTracking.cs
> +    public event UnityAction<Ground> TriggerEnterGroundEvent;
https://trello.com/c/CsOZfMhi/1-%D0%BD%D0%B0%D0%B7%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D1%81%D0%BE%D0%B1%D1%8B%D1%82%D0%B8%D0%B9-%D0%BE%D0%B1%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D1%87%D0%B8%D0%BA%D0%BE%D0%B2

2020-06-08 06:59 UTC, HolyMonkey commented on Assets/Scripts/LevelGeneration.cs
> +    [SerializeField] private GroundTracking _onLeft;
_onLeft?

2020-06-08 06:59 UTC, HolyMonkey commented on Assets/Scripts/LevelGeneration.cs
> +public class LevelGeneration : MonoBehaviour
LevelGenerator

2020-06-08 06:59 UTC, HolyMonkey commented on Assets/Scripts/LevelGeneration.cs
> +    private void EnableGrounds(bool defaultValue)
Что за defaultValue?

2020-06-11 15:08 UTC, HolyMonkey requested changes

2020-06-11 15:08 UTC, HolyMonkey commented on Assets/Scripts/Ground.cs
> +            else if (_chanceCoin + _chanceObstacle > chance)
Вот это очень хрупкая связь. У тебя получается шанс обстейкла связан с шансом монетки? Это неявно

2020-06-11 15:08 UTC, HolyMonkey commented on Assets/Scripts/GroundTracking.cs
> +            _countGrounds = Mathf.Clamp(value, 0, int.MaxValue);
Зачем тебе публичный сетер?

2020-06-11 15:20 UTC, vaad23 commented on Assets/Scripts/GroundTracking.cs
> +            _countGrounds = Mathf.Clamp(value, 0, int.MaxValue);
Этот скрипт так же использует Player для отслеживания, находится ли земля "под ногами", для осуществления прижка.

2020-06-11 15:27 UTC, vaad23 commented on Assets/Scripts/Ground.cs
> +            else if (_chanceCoin + _chanceObstacle > chance)
Да, так получилась странная связь. Хотел избежать повторного вызова нахождения случайного числа.

2020-06-30 08:48 UTC, merged